### ISSUE TITLE
[0407] 스크럼

### ISSUE THREAD

**Issue by superfly9** [codesquad-member-2020/todo-11#29]
-어제 한일

-오늘 계획

-본인 컨디션

-공유되어야 할 이슈

**Comment by superfly9** [comment]
미슈
어제 한일
-구현해야 할 기능 정리(샐리와 함께)
오늘 계획
-개발환경 맞추기/html짜보고 함수로 바꾸기
컨디션
-한달만에 운동을 했더니 몸이 너무 아파서 몸살이 났다.이렇게 약할 줄이야
공유되어야 할 이슈
-내일 고등학생 개학이라 학부모 상담이 갑자기 좀 있어서 수학학원을 좀 일찍 가는 관계로 코쿼 대신 카페에 있습니다.
  맡은 바 할 것은 열심히 하고 있을게요.다들 화이팅

**Comment by Hyune-c** [comment]
- 어제 한 일
  - #1 Setup
    - AWS Server
    - mysql DB
    - Project
  - #2 DB Architecture
    - note table 구현
  - #13 1차 목표 구현
    - Swagger 작성
    - setup deploy script
    - GET /api/notes
- 오늘 할 일
  - GET /api/notes/columns
  - POST /api/notes
  - DELETE /api/notes
- 컨디션
  - 양호
- 공유되어야 할 이슈
  - 없음

**Comment by idevjinie** [comment]
- 어제 한 일
  - 기획서 분석
  - 일감 나누기 및 이슈 등록
- 오늘 할 일
  - 인터페이스 구성
  - 구조 분리
- 컨디션
  - 나른함
- 공유되어야 할 이슈
  - 없음

**Comment by sally4405** [comment]
- 어제 한일
  - 기능 요구사항 정리
  - 이슈 등록
- 오늘 계획
  - 개발환경 셋팅
  - html/css 작성
- 본인 컨디션
  - 오랜만에 운동하고 왔더니 힘드네요!
- 공유되어야 할 이슈
  - 없음
